Repository jenstroeger/python-package-template, pull requests merged in 2021-11, with the labels that each got.

#33 docs: update README.md to mention complete list of paths
  README.md
Labels: documentation

#24 ci: add support for Python 3.10
  .github/workflows/check-and-release-main.yml
  .github/workflows/pull-request.yml
  README.md
  setup.py
  tox.ini
Labels: documentation, enhancement, dependencies, configuration

#39 fix: git hook configuration didn’t match package paths anymore
  .pre-commit-config.yaml
  mypy.ini
Labels: bug, configuration
